//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "infra", table_name = "infra_api_error_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub trace_id: String,
    pub user_id: i64,
    pub user_type: i16,
    pub application_name: String,
    pub request_method: String,
    pub request_url: String,
    pub request_params: String,
    pub user_ip: String,
    pub user_agent: String,
    pub exception_time: DateTime,
    pub exception_name: String,
    #[sea_orm(column_type = "Text")]
    pub exception_message: String,
    #[sea_orm(column_type = "Text")]
    pub exception_root_cause_message: String,
    #[sea_orm(column_type = "Text")]
    pub exception_stack_trace: String,
    pub exception_class_name: String,
    pub exception_file_name: String,
    pub exception_method_name: String,
    pub exception_line_number: i32,
    pub process_status: i16,
    pub process_time: Option<DateTime>,
    pub process_user_id: Option<i32>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: i16,
    pub tenant_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
